apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- route.yaml
- ingress.yaml
images:
- name: ghcr.io/dohyun-99/vue_crud_security_keycloak_test
  newTag: "20240221084233"
